default_language_version:
    python: python3.6
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: detect-private-key
    -   id: debug-statements
    -   id: name-tests-test
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
